config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :products
  resources :searches
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category

	def self.search(search)
		if search
			self.all.order(:name).where(['name LIKE ?', "%#{search}%"])
		else
			self.all
		end
	end

	def category_name
		category.try(:name)
	end

	def category_name=(name)
		self.category = Category.find_or_create_by(name: name) if name.present?
	end
  
end

app/models/search.rb
class Search < ApplicationRecord

	def products
	  @products ||= find_products
	end

	private

	def find_products
	  products = Product.order(:name)
	  products = products.where("name like ?", "%#{keywords}%") if keywords.present?
	  products = products.where(category_id: category_id) if category_id.present?
	  products = products.where("price >= ?", min_price) if min_price.present?
	  products = products.where("price <= ?", max_price) if max_price.present?
	  products
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.order(:name).where("name like ?", "%#{params[:term]}%")
  		render json: @categories.map(&:name)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # @products = Product.order("name").page(params[:page]).per_page(5)
    @products = Product.search(params[:search]).page(params[:page]).per_page(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end

  private

  def product_params
    params.require(:product).permit(:price, :name, :released_at, :category_id, :category_name)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

def new
  @search = Search.new
end

def create
  @search = Search.create!(search_params)
  redirect_to @search
end

def show
  @products = Search.find(params[:id]).products.page(params[:page]).per_page(10) 
end
private	

def search_params
	params.require(:search).permit(:keywords, :category_id, :min_price, :max_price)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
      <div class="clear"></div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :released_at %><br />
    <%= f.date_select :released_at %>
  </div>
  <div class="field">
    <%= f.label :category_name %><br />

    <!-- client side rendering, good for small database driven application
      <% f.text_field :category_name, data: {autocomplete_source: Category.order(:name).map(&:name)} %>
      -->

    <!-- server side rendering -->
    <%= f.text_field :category_name, data: {autocomplete_source: categories_path} %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
    <div class="product">
      <h2><%= link_to product.name, product %></h2>
      <div class="details">
        <%= number_to_currency(product.price) %> |
    <% if product.released_at? %>
        Released on <%= product.released_at.strftime("%B %e, %Y") %>
         <% else %>
         Comming Soon
         <% end %>

      </div>
    </div>

app/views/products/_simple_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Product List</h1>

<%= form_tag products_path, :method => 'get' do  %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<%= link_to "Advanced Search", new_search_path %>

<div id="products">
  <%= render @products %>
</div>

<p><%= link_to "New Product", new_product_path %></p>

<%= will_paginate @products, previous_label: h("Previous"), next_label: h("Next") %>

app/views/products/index.js.erb
$('#products').append('<%= j render(@products) %>');
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@products) %>');
<% else %>
  $('.pagination').remove();
<% end %>

<% sleep 1 %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Released at:</b>
  <%= @product.released_at %>
</p>

<b>Categories:</b>

<ul>
    <li><%= @product.category.name  if @product.category %></li>

</ul>

<p>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'All Products', products_path %>
</p>

app/views/searches/_form.html.erb
<%= form_for @search do |f| %>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :min_price, "Price Range" %><br />
    <%= f.text_field :min_price, size: 10 %> -
    <%= f.text_field :max_price, size: 10 %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

app/views/searches/index.html.erb
   <script>  

   $( function() {



   	// Auto complete
    var names = [ "Jörn Zaefferer", "Scott González", "John Resig" ];
 
    var accentMap = {
      "á": "a",
      "ö": "o"
    };
    var normalize = function( term ) {
      var ret = "";
      for ( var i = 0; i < term.length; i++ ) {
        ret += accentMap[ term.charAt(i) ] || term.charAt(i);
      }
      return ret;
    };
 
    $( "#developer" ).autocomplete({
      source: function( request, response ) {
        var matcher = new RegExp( $.ui.autocomplete.escapeRegex( request.term ), "i" );
        response( $.grep( names, function( value ) {
          value = value.label || value.value || value;
          return matcher.test( value ) || matcher.test( normalize( value ) );
        }) );
      }
    });
  } );

</script>



  <div class="ui-widget">
  <form>
  <label for="developer">Developer: </label>
  <input id="developer">
  </form>
</div>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= render 'form' %>

app/views/searches/show.html.erb
<h1>Advanced Search Results </h1>

<%= pluralize(@products.count, "hit")  %> found

<%= render @products %>

<br>

<%= will_paginate @products, previous_label: h("Previous"), next_label: h("Next") %>

app/views/searches/show.js.erb
$('#products').append('<%= j render(@products) %>');
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@products) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>